title: Conference Deadlines
remark: AI/ML/MIR-oriented

description: Countdowns to top ML / CV / MIC conference and special issue deadlines
author: Siddharth Gururani
maintainers: duducheng

domain: "siddgururani.github.io/ai-deadlines/"
baseurl: "ai-deadlines"

github_username: siddgururani
github_repo: ai-deadlines

markdown: kramdown
